package Chatting_App;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ebrar
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    Client client;
    String username;
    public static DefaultListModel lst_messageModel = new DefaultListModel();
    public static DefaultListModel users = new DefaultListModel();
    public static DefaultListModel lst_clientsModel = new DefaultListModel();
    public static DefaultListModel lst_roomsModel = new DefaultListModel();
    public static ArrayList<String> Rooms = new ArrayList();

    public MainScreen(String str) {
        initComponents();
        this.username = str;
        user_content_list.setModel(lst_clientsModel);
        room_list.setModel(lst_roomsModel);
        room_content_list.setModel(lst_messageModel);
        users_list.setModel(users);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        join_btn = new javax.swing.JButton();
        refresh_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        room_list = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        users_list = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        user_content_list = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        room_content_list = new javax.swing.JList<>();
        connection_btn = new javax.swing.JButton();
        room_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        create_room_btn = new javax.swing.JButton();
        new_room_txt = new javax.swing.JTextField();
        send_user_btn = new javax.swing.JButton();
        send_room_btn = new javax.swing.JButton();
        send_room_txt = new javax.swing.JTextField();
        send_user_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(225, 223, 216));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        join_btn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        join_btn.setText("Join Room");
        join_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                join_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 18, 0, 0);
        jPanel1.add(join_btn, gridBagConstraints);

        refresh_btn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        refresh_btn.setText("Refresh Rooms");
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 18, 0, 0);
        jPanel1.add(refresh_btn, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel3.setText("Client Chat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 34, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jScrollPane2.setViewportView(room_list);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 289;
        gridBagConstraints.ipady = 42;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 12, 0, 0);
        jPanel1.add(jScrollPane2, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel2.setText("Room Chat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jScrollPane1.setViewportView(users_list);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 297;
        gridBagConstraints.ipady = 42;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 34, 0, 12);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        jScrollPane4.setViewportView(user_content_list);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 297;
        gridBagConstraints.ipady = 179;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 34, 0, 12);
        jPanel1.add(jScrollPane4, gridBagConstraints);

        jScrollPane3.setViewportView(room_content_list);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 289;
        gridBagConstraints.ipady = 179;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 12, 0, 0);
        jPanel1.add(jScrollPane3, gridBagConstraints);

        connection_btn.setBackground(new java.awt.Color(204, 0, 0));
        connection_btn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        connection_btn.setText("CONNECT");
        connection_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connection_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 122, 0, 0);
        jPanel1.add(connection_btn, gridBagConstraints);

        room_label.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        room_label.setText("Rooms");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 12, 0, 0);
        jPanel1.add(room_label, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel1.setText("Users");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 34, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        create_room_btn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        create_room_btn.setText("Create New Room");
        create_room_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_room_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 7, 0, 0);
        jPanel1.add(create_room_btn, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 138;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 0, 0);
        jPanel1.add(new_room_txt, gridBagConstraints);

        send_user_btn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        send_user_btn.setText("Send To User");
        send_user_btn.setMinimumSize(new java.awt.Dimension(158, 31));
        send_user_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_user_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 191;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 34, 42, 12);
        jPanel1.add(send_user_btn, gridBagConstraints);

        send_room_btn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        send_room_btn.setText("Send To Room");
        send_room_btn.setMinimumSize(new java.awt.Dimension(165, 31));
        send_room_btn.setPreferredSize(new java.awt.Dimension(158, 31));
        send_room_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_room_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 177;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 12, 42, 0);
        jPanel1.add(send_room_btn, gridBagConstraints);

        send_room_txt.setMinimumSize(new java.awt.Dimension(30, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 310;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 12, 0, 0);
        jPanel1.add(send_room_txt, gridBagConstraints);

        send_user_txt.setMinimumSize(new java.awt.Dimension(30, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 318;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 34, 0, 12);
        jPanel1.add(send_user_txt, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connection_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connection_btnActionPerformed
        // TODO add your handling code here:
        client = new Client(this);
        try {
            client.Start(username);
            lst_messageModel.addElement("(Lobby...)");
        } catch (IOException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        connection_btn.setEnabled(false);

    }//GEN-LAST:event_connection_btnActionPerformed

    private void create_room_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_room_btnActionPerformed
        // TODO add your handling code here:
        if (!new_room_txt.getText().equals("")) {
            String roomName = new_room_txt.getText();
            Message msg = new Message(Message.Message_Type.CreateRoom);
            msg.content = roomName;
            client.Send(msg);
            new_room_txt.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Room name cannot be empty");
        }
    }//GEN-LAST:event_create_room_btnActionPerformed

    private void send_user_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_user_btnActionPerformed
        // TODO add your handling code here:
        if (!users_list.getSelectedValue().equals("") | !send_user_txt.getText().equals("")) {
            String text = send_user_txt.getText();
            Message msg = new Message(Message.Message_Type.user_chat, text, client.username, users_list.getSelectedValue());
            client.Send(msg);
            send_user_txt.setText(" ");
        }
    }//GEN-LAST:event_send_user_btnActionPerformed

    private void send_room_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_room_btnActionPerformed
        // TODO add your handling code here:
        String str = send_room_txt.getText();
        Message msg = new Message(Message.Message_Type.room_chat, str, client.username);
        client.Send(msg);
        send_room_txt.setText(" ");
    }//GEN-LAST:event_send_room_btnActionPerformed

    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_btnActionPerformed
        // TODO add your handling code here:
        Message msg = new Message(Message.Message_Type.Refresh);
        client.Send(msg);
    }//GEN-LAST:event_refresh_btnActionPerformed

    private void join_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_join_btnActionPerformed
        // TODO add your handling code here:
        if (!room_list.getSelectedValue().equals("")) {
            client.room = room_list.getSelectedValue();
            Message msg = new Message(Message.Message_Type.JoinRoom);
            msg.content = room_list.getSelectedValue();
            client.Send(msg);
            lst_messageModel.removeAllElements();
            lst_messageModel.addElement("(Now Talking To " + client.room + ")");
        } else {
            JOptionPane.showMessageDialog(this, "Please Select A Room ");
        }
    }//GEN-LAST:event_join_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connection_btn;
    private javax.swing.JButton create_room_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton join_btn;
    private javax.swing.JTextField new_room_txt;
    private javax.swing.JButton refresh_btn;
    private javax.swing.JList<String> room_content_list;
    private javax.swing.JLabel room_label;
    private javax.swing.JList<String> room_list;
    private javax.swing.JButton send_room_btn;
    private javax.swing.JTextField send_room_txt;
    private javax.swing.JButton send_user_btn;
    private javax.swing.JTextField send_user_txt;
    private javax.swing.JList<String> user_content_list;
    private javax.swing.JList<String> users_list;
    // End of variables declaration//GEN-END:variables
}
